project/config/routes.rb
Rails.application.routes.draw do

  resources :event_lists

  resources :vehicles

  resources :user_profiles

  resources :users

  root controller: 'home', action: 'index'

get "/ride", controller: 'home', action: 'ride'
get "/drive", controller: 'home', action: 'drive'
get "/signin", controller: 'home', action: 'signin'
get "/signup", controller: 'home', action: 'signup'

end

project/app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  validates_presence_of :userName, :age, :gender, :streetAddress, :City, :State, :Zip
  validates :userName, presence: true, uniqueness: true
end

project/app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:userName, :age, :gender, :streetAddress, :City, :State, :Zip, :profilePicUrl)
    end
end

project/app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

project/app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userName %><br>
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :streetAddress %><br>
    <%= f.text_field :streetAddress %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :State %><br>
    <%= f.text_field :State %>
  </div>
  <div class="field">
    <%= f.label :Zip %><br>
    <%= f.text_field :Zip %>
  </div>
  <div class="field">
    <%= f.label :profilePicUrl %><br>
    <%= f.text_field :profilePicUrl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

project/app/views/user_profiles/index.html.erb
<h1>User Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th></th>
      <th>Age</th>
      <th></th>
      <th>Gender</th>
      <th></th>
      <th>Streetaddress</th>
      <th></th>
      <th>City</th>
      <th></th>
      <th>State</th>
      <th></th>
      <th>Zip</th>
      <th></th>
      <th>Profilepicurl</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.userName %></td>
        <td><%= user_profile.age %></td>
        <td><%= user_profile.gender %></td>
        <td><%= user_profile.streetAddress %></td>
        <td><%= user_profile.City %></td>
        <td><%= user_profile.State %></td>
        <td><%= user_profile.Zip %></td>
        <td><%= user_profile.profilePicUrl %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

project/app/views/user_profiles/new.html.erb
<h1>New User Profile</h1>

<%= render 'form' %>

project/app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user_profile.userName %>
</p

<p>
  <strong>Age:</strong>
  <%= @user_profile.age %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @user_profile.gender %>
</p>
<p>
  <strong>Streetaddress:</strong>
  <%= @user_profile.streetAddress %>
</p>
<p>
  <strong>City:</strong>
  <%= @user_profile.City %>
</p>
<p>
  <strong>State:</strong>
  <%= @user_profile.State %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @user_profile.Zip %>
</p>

<p>
  <strong>Profilepicurl:</strong>
  <%= @user_profile.profilePicUrl %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>