project/config/routes.rb
Rails.application.routes.draw do

  resources :event_lists

  resources :vehicles

  resources :user_profiles

  resources :users

  root controller: 'home', action: 'index'

get "/ride", controller: 'home', action: 'ride'
get "/drive", controller: 'home', action: 'drive'
get "/signin", controller: 'home', action: 'signin'
get "/signup", controller: 'home', action: 'signup'

end

project/app/models/event_list.rb
class EventList < ActiveRecord::Base
  validates_presence_of :eventName, :eventDescription, :streetAddress, :City, :State, :Zip, :nbrOfRiders, :vehicleType, :PUstreetAddress, :PUCity, :PUState, :PUZip, :createdBy

  def self.find_all_by_query(query)
  query = query.downcase
  query = "%#{query}%"
  EventList.where(['lower(eventName) like ?
  OR lower(eventDescription) like ?
  OR lower(City) like ?',
  query, query, query])
  end

end

project/app/controllers/event_lists_controller.rb
class EventListsController < ApplicationController
  before_action :set_event_list, only: [:show, :edit, :update, :destroy]

  # GET /event_lists
  # GET /event_lists.json
  def index
    if params[:q]
    @event_lists = EventList.find_all_by_query(params[:q])
    else
    @event_lists = EventList.all
    end
  end

  # GET /event_lists/1
  # GET /event_lists/1.json
  def show
  end

  # GET /event_lists/new
  def new
    @event_list = EventList.new
  end

  # GET /event_lists/1/edit
  def edit
  end

  # POST /event_lists
  # POST /event_lists.json
  def create
    @event_list = EventList.new(event_list_params)

    respond_to do |format|
      if @event_list.save
        format.html { redirect_to @event_list, notice: 'Event list was successfully created.' }
        format.json { render :show, status: :created, location: @event_list }
      else
        format.html { render :new }
        format.json { render json: @event_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_lists/1
  # PATCH/PUT /event_lists/1.json
  def update
    respond_to do |format|
      if @event_list.update(event_list_params)
        format.html { redirect_to @event_list, notice: 'Event list was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_list }
      else
        format.html { render :edit }
        format.json { render json: @event_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_lists/1
  # DELETE /event_lists/1.json
  def destroy
    @event_list.destroy
    respond_to do |format|
      format.html { redirect_to event_lists_url, notice: 'Event list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_list
      @event_list = EventList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_list_params
      params.require(:event_list).permit(:eventDate, :eventTime, :eventName, :eventDescription, :streetAddress, :City, :State, :Zip, :nbrOfRiders, :vehicleType, :PUstreetAddress, :PUCity, :PUState, :PUZip, :smokingAllowed, :createdBy, :eventDriver)
    end
end

project/app/helpers/event_lists_helper.rb
module EventListsHelper
end

project/app/views/event_lists/_form.html.erb
<%= form_for(@event_list) do |f| %>
  <% if @event_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_list.errors.count, "error") %> prohibited this event_list from being saved:</h2>

      <ul>
      <% @event_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eventDate %><br>
    <%= f.date_select :eventDate %>
  </div>
  <div class="field">
    <%= f.label :eventTime %><br>
    <%= f.time_select :eventTime %>
  </div>
  <div class="field">
    <%= f.label :eventName %><br>
    <%= f.text_area :eventName %>
  </div>
  <div class="field">
    <%= f.label :eventDescription %><br>
    <%= f.text_area :eventDescription %>
  </div>
  <div class="field">
    <%= f.label :streetAddress %><br>
    <%= f.text_area :streetAddress %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_area :City %>
  </div>
  <div class="field">
    <%= f.label :State %><br>
    <%= f.text_area :State %>
  </div>
  <div class="field">
    <%= f.label :Zip %><br>
    <%= f.text_area :Zip %>
  </div>
  <div class="field">
    <%= f.label :nbrOfRiders %><br>
    <%= f.number_field :nbrOfRiders %>
  </div>
  <div class="field">
    <%= f.label :vehicleType %><br>
    <%= f.text_area :vehicleType %>
  </div>
  <div class="field">
    <%= f.label :PUstreetAddress %><br>
    <%= f.text_area :PUstreetAddress %>
  </div>
  <div class="field">
    <%= f.label :PUCity %><br>
    <%= f.text_area :PUCity %>
  </div>
  <div class="field">
    <%= f.label :PUState %><br>
    <%= f.text_area :PUState %>
  </div>
  <div class="field">
    <%= f.label :PUZip %><br>
    <%= f.text_area :PUZip %>
  </div>
  <div class="field">
    <%= f.label :smokingAllowed %><br>
    <%= f.check_box :smokingAllowed %>
  </div>
  <div class="field">
    <%= f.label :createdBy %><br>
    <%= f.text_area :createdBy %>
  </div>
  <div class="field">
    <%= f.label :eventDriver %><br>
    <%= f.check_box :eventDriver %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/event_lists/edit.html.erb
<h1>Editing event_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_list %> |
<%= link_to 'Back', event_lists_path %>

project/app/views/event_lists/index.html.erb
<h1>Events Listing</h1>

<%= render "/shared/search" %>

<table>
  <thead>
    <tr>
      <th>Eventdate</th>
      <th>Eventtime</th>
      <th>Eventname</th>
      <th>Eventdescription</th>
      <th>Streetaddress</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Nbrofriders</th>
      <th>Vehicletype</th>
      <th>Pustreetaddress</th>
      <th>Pucity</th>
      <th>Pustate</th>
      <th>Puzip</th>
      <th>Smokingallowed</th>
      <th>Createdby</th>
      <th>Eventdriver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_lists.each do |event_list| %>
      <tr>
        <td><%= event_list.eventDate %></td>
        <td><%= event_list.eventTime %></td>
        <td><%= event_list.eventName %></td>
        <td><%= event_list.eventDescription %></td>
        <td><%= event_list.streetAddress %></td>
        <td><%= event_list.City %></td>
        <td><%= event_list.State %></td>
        <td><%= event_list.Zip %></td>
        <td><%= event_list.nbrOfRiders %></td>
        <td><%= event_list.vehicleType %></td>
        <td><%= event_list.PUstreetAddress %></td>
        <td><%= event_list.PUCity %></td>
        <td><%= event_list.PUState %></td>
        <td><%= event_list.PUZip %></td>
        <td><%= event_list.smokingAllowed %></td>
        <td><%= event_list.createdBy %></td>
        <td><%= event_list.eventDriver %></td>
        <td><%= link_to 'Show', event_list %></td>
        <td><%= link_to 'Edit', edit_event_list_path(event_list) %></td>
        <td><%= link_to 'Destroy', event_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event list', new_event_list_path %>

project/app/views/event_lists/new.html.erb
<h1>Create new event</h1>

<%= render 'form' %>

<%= link_to 'Back', event_lists_path %>

project/app/views/event_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Eventdate:</strong>
  <%= @event_list.eventDate %>
</p>

<p>
  <strong>Eventtime:</strong>
  <%= @event_list.eventTime %>
</p>

<p>
  <strong>Eventname:</strong>
  <%= @event_list.eventName %>
</p>

<p>
  <strong>Eventdescription:</strong>
  <%= @event_list.eventDescription %>
</p>

<p>
  <strong>Streetaddress:</strong>
  <%= @event_list.streetAddress %>
</p>

<p>
  <strong>City:</strong>
  <%= @event_list.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @event_list.State %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @event_list.Zip %>
</p>

<p>
  <strong>Nbrofriders:</strong>
  <%= @event_list.nbrOfRiders %>
</p>

<p>
  <strong>Vehicletype:</strong>
  <%= @event_list.vehicleType %>
</p>

<p>
  <strong>Pustreetaddress:</strong>
  <%= @event_list.PUstreetAddress %>
</p>

<p>
  <strong>Pucity:</strong>
  <%= @event_list.PUCity %>
</p>

<p>
  <strong>Pustate:</strong>
  <%= @event_list.PUState %>
</p>

<p>
  <strong>Puzip:</strong>
  <%= @event_list.PUZip %>
</p>

<p>
  <strong>Smokingallowed:</strong>
  <%= @event_list.smokingAllowed %>
</p>

<p>
  <strong>Createdby:</strong>
  <%= @event_list.createdBy %>
</p>

<p>
  <strong>Eventdriver:</strong>
  <%= @event_list.eventDriver %>
</p>

<%= link_to 'Edit', edit_event_list_path(@event_list) %> |
<%= link_to 'Back', event_lists_path %>