project/config/routes.rb
Rails.application.routes.draw do

  resources :event_lists

  resources :vehicles

  resources :user_profiles

  resources :users

  root controller: 'home', action: 'index'

get "/ride", controller: 'home', action: 'ride'
get "/drive", controller: 'home', action: 'drive'
get "/signin", controller: 'home', action: 'signin'
get "/signup", controller: 'home', action: 'signup'

end

project/app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :userName, :firstName, :lastName, :Email, :phone, :password
  validates :userName, presence: true, uniqueness: true
  validates :Email, presence: true, uniqueness: true
  validates_format_of :Email, :with => /.+@.+\..+/i
end

project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @number_of_users = User.count
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:userName, :firstName, :lastName, :Email, :phone, :password)
    end
end

project/app/helpers/users_helper.rb
module UsersHelper
end

project/app/views/users/_form.html.erb
<head>
  <meta charset="utf-8">
  <title>Chippewa Valley - The One</title>
  <link rel="stylesheet" href="../stylesheets/application.css" type="text/css"/>
  <link rel="stylesheet" href="../stylesheets/home.css.scss" type="text/css"/>
</head>
<body>
  <div class="titles">
       <h1>Sign up today and start ridesharing</h1>
       <h3>It's free to sign up!</h3>
</div>
<%= form_for(@user) do |f| %>
  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :userName %><br>
    <%= f.text_area :userName %>
  </div>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_area :firstName %>
  </div>

  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_area :lastName %>
  </div>

  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_area :Email %>
  </div>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
    
<%= link_to 'Sign Up your Vehicle', new_vehicle_path %>
<%= link_to 'Create your profile', new_user_profile_path %>
  
<% end %>
    <p>Already have an account? <a href="/signin">Click here to sign in</a></p>
  
</body>
<div>
<footer>Copyright &copy; CVTC-Agile Fall 2017 Griffendor Team</footer>
</div>

project/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

project/app/views/users/index.html.erb
<h1>Listing users</h1>

<p>There are <%= @number_of_users %> users total.</p>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.userName %></td>
        <td><%= user.firstName %></td>
        <td><%= user.lastName %></td>
        <td><%= user.Email %></td>
        <td><%= user.phone %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= button_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path %>

project/app/views/users/new.html.erb
<%= render 'form' %>

<!--
<%= link_to 'Back', users_path %>
-->

project/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.userName %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |